import React from 'react';
import BlogPostPage from '@theme-original/BlogPostPage';
import Head from '@docusaurus/Head';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';

/**
 * Wraps BlogPostPage to inject a per-post og:image meta tag whose path matches
 * the image generated by scripts/generate-og-images.mjs.
 *
 * Convention: /assets/img/og/posts/<permalink-without-slashes>.png
 */
export default function BlogPostPageWrapper(props) {
  const {siteConfig} = useDocusaurusContext();
  const permalink = props?.content?.metadata?.permalink ?? '';

  // Strip leading/trailing slashes to form the filename stem.
  const slug = permalink.replace(/^\/|\/$/g, '');

  const ogImageUrl = slug
    ? `${siteConfig.url}/assets/img/og/posts/${slug}.png`
    : null;

  return (
    <>
      {ogImageUrl && (
        <Head>
          <meta property="og:image" content={ogImageUrl} />
          <meta name="twitter:image" content={ogImageUrl} />
          <meta name="twitter:card" content="summary_large_image" />
        </Head>
      )}
      <BlogPostPage {...props} />
    </>
  );
}
